name: Update                   

on:
  workflow_dispatch: {}
  schedule:
  - cron: "27 * * * *"

jobs:   
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8                         
      uses: actions/setup-python@v2
      with:
        python-version: 3.8                         
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Download & process data
      run: |
        python download.py
        jupyter nbconvert --to html --TemplateExporter.exclude_input=True --no-prompt --execute hospi.ipynb --output docs/hospi.html
        jupyter nbconvert --to html --TemplateExporter.exclude_input=True --no-prompt --execute cases.ipynb --output docs/cases.html
        jupyter nbconvert --to html --TemplateExporter.exclude_input=True --no-prompt --execute covid-deaths.ipynb --output docs/covid-deaths.html
        jupyter nbconvert --to html --TemplateExporter.exclude_input=True --no-prompt --execute cases-age-groups.ipynb --output docs/cases-age-groups.html
        jupyter nbconvert --to html --TemplateExporter.exclude_input=True --no-prompt --execute vaccines.ipynb --output docs/vaccines.html
        jupyter nbconvert --to html --TemplateExporter.exclude_input=True --no-prompt --execute mortality-statbel.ipynb --output docs/mortality-statbel.html
        jupyter nbconvert --to html --TemplateExporter.exclude_input=True --no-prompt --execute mobility-google.ipynb --output docs/mobility-google.html


    - name: Commit the new processed data
      run: |
        git pull
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
